### ISSUE TITLE
Reporting BF results

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#153]
I'm a bit confused and perplexed by how it currently reports BF results (helpers_bf_tests).  This is solely in the case of `posterior = FALSE` ...

1.  Why are we reporting by default BF01 (support for the null hypothesis) when most researchers are interested in support for their alternative research hypothesis.

2.  Why are we reporting with various logs and exponents even for the cases when the BF is a modest number?  Results like loge(BF01) = -65.10 don't exactly lend themselves to clarity...

Was this a standard suggested by an outside source or reference standard?

I'd like to take a run at rewriting it to format based on the size of BF10 if it's not too big leave it alone.  This will have the side benefit of simplifying the code immensely since as you know you can extract BF10 directly from the BFBayesFactor object

``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
library(ggstatsplot)
# In this case I agree the produced BF10 is unwieldly but 
# loge(BF01) = -65.10 is pretty cryptic
ggbetweenstats(iris, Species, Sepal.Length, bf.message = TRUE)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for Sepal.Length : p-value = 0.010
#> 
#> Note: Bartlett's test for homogeneity of variances for factor Species : p-value = < 0.001
#> 
```

![](https://i.imgur.com/3YHdaqo.png)

``` r

extractBF(BayesFactor::anovaBF(Sepal.Length ~ Species,
                               data = iris))
#>                   bf        error                     time         code
#> Species 1.425293e+28 6.507104e-08 Wed Jan 30 17:26:00 2019 1c0d77d706ba
extractBF(BayesFactor::anovaBF(Sepal.Length ~ Species,
                               data = iris), 
  onlybf = TRUE)
#> [1] 1.425293e+28

# in this case In favor of BF10 = 86.58973 rounded is pretty easy
# and the researcher really wants to know the data support her
# hypothesis 86.6:1 not that the null is 0.012:1
# I propose to flip as needed.
mtcars$am <- factor(mtcars$am)
ggbetweenstats(mtcars, am, mpg, bf.message = TRUE)
#> Note: Shapiro-Wilk Normality Test for mpg : p-value = 0.123
#> 
#> Note: Bartlett's test for homogeneity of variances for factor am : p-value = 0.072
#> 
```

![](https://i.imgur.com/xMGJbpT.png)

``` r
extractBF(BayesFactor::anovaBF(mpg ~ am, data = mtcars),
  onlybf = TRUE)
#> [1] 86.58973
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
All of this is actually intentional. So there are two ways in which the Bayesian statistics is expected to be used in `ggstatsplot`-

- As primary analysis

If you want to do **just** Bayesian analysis, then you will get `BF10` value. For example,

``` r
library(ggstatsplot)

ggbetweenstats(iris, Species, Sepal.Length, type = "bf")
#> Note: Shapiro-Wilk Normality Test for Sepal.Length : p-value = 0.010
#> 
#> Note: Bartlett's test for homogeneity of variances for factor Species : p-value = < 0.001
#> 
```

![](https://i.imgur.com/hx6MTse.png)


- As complementary analysis

This is supposed to be used when you are relying on frequentist statitstics to draw inference, find a null effect, and then want to quantify support for null using Bayes Factor (as suggested here: https://journals.sagepub.com/doi/abs/10.1177/2515245918773742) using `BF01`. For example,

(In this case, this is not really helpful because the effect is significant. But you get the point.)
``` r
library(ggstatsplot)

ggbetweenstats(iris, Species, Sepal.Length, type = "p", bf.message = TRUE)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for Sepal.Length : p-value = 0.010
#> 
#> Note: Bartlett's test for homogeneity of variances for factor Species : p-value = < 0.001
#> 
```

![](https://i.imgur.com/oe6bn99.png)

As for using log values, I just want the results to be consistent in terms of what's being displayed. If BF values are sometimes log-transformed, while other times not, it will get pretty confusing.
(Other softwares provide this option as well)
![image](https://user-images.githubusercontent.com/11330453/52022512-2d620080-24c7-11e9-9379-3f9c08cc29bd.png)

That said, I am soon going to rewrite these functions to follow these guidelines-
https://psyarxiv.com/yqxfr

I will leave these functions as they are for now to not have merge conflicts and prioritize the effect size calculation for non-parametric tests.

**Comment by ibecav** [comment]
Thanks.  Understand the background.  I wish they had chosen the more conservative Kass & Raftery, 1995 rather than the looser Jeffreys, 1939.

Since most of my audiences are much more familiar with frequentist methods I like the notion of reporting those frequentist results in the sub-title but for me being able to include the BF in the caption is very useful.

I hope eventually we'll get to a place  where reporting the logged BF is never necessary, at some point it becomes almost silly like taking p out to p = .00000015678.  If a BF > 150 using Kass & Rafferty is **_very strong_** or **_strong_**  with Jeffrey then people get that a BF > 1,000 is **_super duper strong_** or **_mega strong_** but scientific notation with a minimum number of decimal places is probably good enough after all a million to one is much easier to process as a statement of evidentiary support than 1.234567e6 : 1 or exp(14.02623) : 1

To the iris example above the BF is 1.425293e+28 which is a ridiculously large number better people have a sense that's bigger than your [chances of winning a billion dollar Powerball](https://www.cbsnews.com/news/odds-of-winning-1-billion-mega-millions-and-powerball-1-in-88-quadrillion/)
