### ISSUE TITLE
let `effsize_t_parametric` handle unequal variance?

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#165]
@ibecav The default for `ggbetweenstats` is `var.equal = FALSE`, which means we run Welch's _t_-test by default. But the effect size we currently display is based on the `var.equal = TRUE`.  So there is a slight discrepancy between how statistic and effect size for the same test are being computed.

Maybe `effsize_t_parametric` can gain a new argument `var.equal` that deals with this **for between-subjects designs**? What do you think?

``` r
ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = FALSE,
  messages = FALSE
)
```

![](https://i.imgur.com/Y3YzMZ7.png)

`JASP` implements this properly-

![image](https://user-images.githubusercontent.com/11330453/52796568-16ccb500-3042-11e9-8f41-cecf655a84e8.png)

**Comment by ibecav** [comment]
Looking at this this afternoon. Certainly possible first pass I get d/g within .01 to them but CIs are oddly different so will take a bit to figure out

**Comment by ibecav** [comment]
About to submit a PR that accounts for this.  They are definitely using NCP (apparently with no option to go the other way). 

To be efficient about it I had to more closely tie the effect size calcualtions to the t-test you were already running (easier to grab the Welch's df but it also makes sure things stay in sync).  The  downsides are that:

1.  `effsize_t_parametric` really probably shouldn't be exported anymore
2. You have to build the `tobject` to test it directly.

Took me a very long time to fix all the tests you carefully wrote.  

There's a sign issue with the ncp variant that is pretty intractable.  My recommendation si we report absolute values for `d` and `g` and their confidence intervals (this is pretty common practice but I'll admit not universal).  Not sufre how soon i chase down the sign issue otherwise.  It only crops up when ncp is on and the effect has a minus sign and the confidence interval flops.

``` r
library(ggstatsplot)
# using the titles to show the 4 combinations
ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = FALSE,
  var.equal = TRUE,
  k = 4,
  title = "Student's t & Cohen's D & no ncp",
  messages = FALSE
)
```

![](https://i.imgur.com/McshkkL.png)

``` r

ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = FALSE,
  var.equal = FALSE,
  k = 4,
  title = "Welch's t & Cohen's D & no ncp",
  messages = FALSE
)
```

![](https://i.imgur.com/UsYQc3T.png)

``` r

ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = TRUE,
  var.equal = TRUE,
  k = 4,
  title = "Student's t & Cohen's D & with ncp",
  messages = FALSE
)
```

![](https://i.imgur.com/f2SuOYs.png)

``` r

ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = TRUE,
  var.equal = FALSE,
  k = 4,
  title = "Welch's t & Cohen's D & with ncp",
  messages = FALSE
)
```

![](https://i.imgur.com/Ug49rVw.png)

``` r

ggstatsplot::subtitle_t_parametric(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = TRUE,
  var.equal = TRUE,
  k = 4,
  title = "Student's t & Cohen's D & with ncp",
  messages = FALSE
)
#> paste(NULL, italic("t"), "(", "30", ") = ", "5.2576", ", ", italic("p"), 
#>     " = ", "< 0.001", ", ", italic("d"), " = ", "1.8924", ", CI"["99%"], 
#>     " [", "0.7672", ", ", "3.0050", "]", ", ", italic("n"), " = ", 
#>     32L)

ggstatsplot::subtitle_t_parametric(
  data = mtcars,
  x = am,
  y = wt,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = TRUE,
  var.equal = FALSE,
  k = 4,
  title = "Welch's t & Cohen's D & with ncp",
  messages = FALSE
)
#> paste(NULL, italic("t"), "(", "29.2335", ") = ", "5.4939", ", ", 
#>     italic("p"), " = ", "< 0.001", ", ", italic("d"), " = ", 
#>     "1.9349", ", CI"["99%"], " [", "0.8318", ", ", "3.1113", 
#>     "]", ", ", italic("n"), " = ", 32L)
```

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
This is awesome, Chuck!

1. Yes, I agree that we should no longer export effsize_t_parametric.
2. I agree with you on the sign issue; it's not very helpful information for interpreting these effect sizes. But just to have a better understanding of this, what do you get if you run the following code with the PR changes?
```
ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = am,
  y = mpg,
  conf.level = 0.99,
  effsize.type = "d",
  effsize.noncentral = TRUE,
  var.equal = TRUE,
  k = 4,
  title = "Student's t & Cohen's D & with ncp",
  messages = FALSE
)
```

**Comment by IndrajeetPatil** [comment]
Never mind, all of this looks good to me. I have already merged these changes into master.

**Comment by ibecav** [comment]
Thank you just got back to my desk
