### ISSUE TITLE
polygon edge not found

### ISSUE THREAD

**Issue by f4bry** [IndrajeetPatil/ggstatsplot#178]
Hi, 
When running your examples I got the following error:

```r
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
```
Any idea how to fix it?

I am working with RStudio (Version 1.1.456), R version 3.5.2 (2018-12-20), Mac OS X 10.14.1

Thank you!
F.

**Comment by IndrajeetPatil** [comment]
Can you give more information? Which example?

At any rate, I am pretty sure this has nothing to do with `ggstatsplot` code. Have a look at this-
https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon

**Comment by f4bry** [comment]
...but hiding some comments, as in the following example, makes it working:
```r
ggstatsplot::grouped_ggscatterstats(
  data = dplyr::filter(
    .data = ggstatsplot::movies_long,
    genre %in% c("Action", "Action Comedy", "Action Drama", "Comedy")
  ),
  x = rating,
  y = length,
  #bf.message = TRUE,      # display bayes factor message
  conf.level = 0.99,
  k = 3,                  # no. of decimal places in the results
  xfill = "#E69F00",
  yfill = "#8b3058",
  #xlab = "IMDB rating",
  grouping.var = genre,   # grouping variable
  #title.prefix = "Movie genre",
  ggtheme = ggplot2::theme_grey(),
  ggplot.component = list(
    ggplot2::scale_x_continuous(breaks = seq(2, 9, 1), limits = (c(2, 9)))
  ),
  #messages = FALSE,
  nrow = 2,
  ncol = 2#,
  #title.text = "Relationship between movie length by IMDB ratings for different genres"
)

```

**Comment by f4bry** [comment]
> Can you give more information? Which example?
> 
> At any rate, I am pretty sure this has nothing to do with `ggstatsplot` code. Have a look at this-
> https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon

I tried what they suggest and it didn't fix it.
F.

**Comment by IndrajeetPatil** [comment]
Yeah, this is definitely coming from `ggplot2` (or `grid` rather) in `RStudio`. Nothing I can do about it but wait for it to be resolved:
https://github.com/dipetkov/eems/issues/32

**Comment by IndrajeetPatil** [comment]
Also, have you tried running the example in RMarkdown document and then knitting it? Does that work?

**Comment by f4bry** [comment]
Ok, thank you!

**Comment by f4bry** [comment]
> Also, have you tried running the example in RMarkdown document and then knitting it? Does that work?

Not yet, I will! thanks!

**Comment by ibecav** [comment]
It's specific to Macs and as a Mac user it used to drive me cray until I stumbled upon this...

Happy New Year!

Thanks for the tip! I owe you big time.  I installed the preview release before the holidays and I can say that it has worked flawlessly with no unintended consequences.  Literally saves me minutes every day not to mention tons of frustration avoided.

On Thu, Dec 20, 2018 at 1:25 PM Dana Seidel <dana.seidel@gmail.com> wrote:
Great news! The Rstudio Preview version (https://www.rstudio.com/products/rstudio/download/preview/) contains a workaround since October. I haven't tested it myself but trust they've at least patched the issue. 
And in case you're like me and don't always get around to updating my software right away, yes!, there are a couple easy workarounds! The easiest thing is to do is to specify any other graphics device: `png()`, `pdf()`, etc. before plotting - none of these have this issue. OR since the error is triggered by special characters in the axis tick labels you can simply change the tick labels manually in with a scale command or drop the axis labels entirely using theme. 

Hope this helps! Glad you enjoyed the blog -only wish I had time to write more! 
Best, 
Dana
