### ISSUE TITLE
gghistostats - superimpose kernel density plot

### ISSUE THREAD

**Issue by xmarti6** [IndrajeetPatil/ggstatsplot#214]
Hi, would it be possible to super-impose the kernel density plot (not the normal curve) in the "gghistostats" chart? that way, in my point of view, it is easier to compare the normal curve against the current distribution.
I was able to plot something similar by adding this in the "gghistostats" function, which tries to calc the default bandwidth and scale using the max-count value obtained by the "hist" function.
```
 ggplot.component =  geom_line(  
          aes(y = (..scaled..) * (  max( 
                                           hist(  subset(x=df,subset= variable==k)$value, 
                                                  floor( (max(!!aes(x)$x) - min(!!aes(x)$x))/sqrt( max(table(df$variable)) ) ) , 
                                                  plot = FALSE
                                                 )$counts
                                      )  )
          ) , stat="density", size = 1, colour="red", linetype=2))
```
But I belive this scaling is wrong.
Many thanks

**Comment by IndrajeetPatil** [comment]
@ibecav Do you want to have a look at this?

**Comment by ibecav** [comment]
@xmarti6 not to be argumentative but to check.  I've always found superimposing density on histogram just a little odd since binning makes all the difference.  Seems to me if you want density then you might as well compare to theoretical normal since they are on the same scale.

Please see this reprex.

``` r
library(CGPfunctions)

SeeDist(mtcars$hp, whatvar = "Horsepower", whatplots = c("d"))
```

![](https://i.imgur.com/4srLgAk.png)

    #>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    #>    52.0    96.5   123.0   146.7   180.0   335.0

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
