### ISSUE TITLE
Shapiro-Wilk test

### ISSUE THREAD

**Issue by tkaiser86** [IndrajeetPatil/ggstatsplot#24]
When I try to plot between-group statistics with ggbetweenstats, it fails for samples larger than 5000 because of the Shapiro-Wilk test:

```r
dat <- data.frame(x = c(rep(1,2500),rep(2,2501)), y = rnorm(5001))
ggbetweenstats(data = dat, x = x, y = y)
Warning:  aesthetic `x` was not a factor; converting it to factor
Reference:  Welch's t-test is used as a default. (Delacre, Lakens, & Leys, International Review of Social Psychology, 2017).
Error in stats::shapiro.test(data$y) :
  sample size must be between 3 and 5000
```

This could be fixed easily by using ks.test(y, "pnorm") instead.

**Comment by IndrajeetPatil** [comment]
Thanks for pointing out this issue. I've now changed the default normality test from Shapiro-Wilk test to  Anderson-Darling (AD) test. I am reluctant to use Kolmogorov-Smirnov (KS) test because-

1. results from KS test can be pretty misleading (https://asaip.psu.edu/Articles/beware-the-kolmogorov-smirnov-test);
2. AS is more powerful than KS 
(Razali, Nornadiah; Wah, Yap Bee (2011). Power comparisons of Shapiro–Wilk, Kolmogorov–Smirnov, Lilliefors and Anderson–Darling tests. _Journal of Statistical Modeling and Analytics_. 2 (1): 21–33. ) 

At any rate, the normality test won't fail now, either in case of `ggbetweenstats` or `gghistostats` (if you have sample size less than 7, which AD test can't handle, the normality test won't be carried out):
``` r
library(ggstatsplot)
dat <- data.frame(x = c(rep(1, 2500), rep(2, 2501)), y = rnorm(5001))
ggstatsplot::ggbetweenstats(data = dat, x = x, y = y)
#> Warning:  aesthetic `x` was not a factor; converting it to factor
#> 
#> Reference:  Welch's t-test is used as a default. (Delacre, Lakens, & Leys, International Review of Social Psychology, 2017).
#> 
#> Note:  Anderson-Darling Normality Test for y : p-value =  0.713
#> 
#> Note:  Bartlett's test for homogeneity of variances for factor x : p-value =  0.512
#> 
```

![](https://i.imgur.com/y1If6I1.png)

``` r
ggstatsplot::gghistostats(data = dat, x = x)
#> Note:  Anderson-Darling Normality Test for x : p-value =  < 0.001
#> 
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/gWftA13.png)

Created on 2018-03-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
