### ISSUE TITLE
When marginal=TRUE on ggscatterstats, graphs does display when you run the chunk within an R notebook

### ISSUE THREAD

**Issue by ethulin** [IndrajeetPatil/ggstatsplot#28]
This issue appears to be specific to running a chunk within an R notebook.

When I run ggscatterstats within a chunk in an R notebook with marginal=TRUE, I get the error "Warning: This function doesn't return ggplot2 object and is not further modifiable with ggplot2 commands."

Here is my code:

```{r}
library(ggstatsplot)
ggscatterstats(cars,speed,dist,marginal=TRUE)
```

I should note I also tried with messages=FALSE. That suppressed the message, but did not render the plot.

And for clarity, here is a screen shot of it not working with marginal, and working without marginal.

![image](https://user-images.githubusercontent.com/19850662/39763263-9f15e150-52aa-11e8-869e-6d6b9bd166aa.png)

I love those histograms, so I hope there is a way to do this in notebooks!

**Comment by IndrajeetPatil** [comment]
Here is how you can get the code chunk to run within `R Notebook` or `R Markdown`:

![image](https://user-images.githubusercontent.com/11330453/39766523-841c0dea-52b2-11e8-8871-12683e528cae.png)

This is because `ggscatterstats` relies on function `ggExtra`. Check out the section titled here (`Using ggMarginal() in R Notebooks or Rmarkdown`):
https://github.com/daattali/ggExtra

**Comment by ethulin** [comment]
Thanks!

Going to be yukky to have to keep doing that for every scatterplot, but maybe there will be some way to resolve it in ggExtra in the future.

**Comment by IndrajeetPatil** [comment]
@ethulin With the new version of `ggExtra`, this issue should no longer exist! No more workarounds in Notebooks, etc. I hope that's the case for you.
