### ISSUE TITLE
RM mixed Anova 

### ISSUE THREAD

**Issue by DanDKL** [IndrajeetPatil/ggstatsplot#310]
Hi,
I really want to say that ggstatsplot is brilliant. I'm basically doing all the plots with this right now. :) thank you for all the work and the effort you put in to it.

The one thing I'm missing is a way to do a RM mixed anova, e.g. within: time (2 factors, pre_scores and post_scores) and between: Group (2 groups, treatment and controll).
It is a pretty basic analisys, is there a work around with the current package? or, do you plan to implement it soon?

Thanks again

**Comment by IndrajeetPatil** [comment]
Same as https://github.com/IndrajeetPatil/ggstatsplot/issues/262. 

Please have a look at my answer in that thread:
https://github.com/IndrajeetPatil/ggstatsplot/issues/262#issuecomment-520269611

There are currently no plans to implement this since it is not straightforward to me as to how this can be done.
