### ISSUE TITLE
CRAN submission, (reverse) dependency issues

### ISSUE THREAD

**Issue by strengejacke** [IndrajeetPatil/ggstatsplot#327]
Due to changes in one of the suggested packages of [insight](https://cran.r-project.org/package=insight), I need to send an update to CRAN. However, some changes affect the _sjstats_ package, which I need to submit to CRAN before. _sjstats_, in turn, now deprecates `sjstats::p_value()`, which will break your package. I already saw that you replaced `sjstats::p_value()` with `parameters::p_value()`, so my question is, are you able to submit an update of _ggstatsplot_ very soon to CRAN? Else, I would rather "soft-deprecate" `sjstats::p_value()`, to make it work with the current CRAN version of _ggstatsplot_.

**Comment by IndrajeetPatil** [comment]
Hi Daniel, Thanks for getting in touch about this.

I planned to submit a new version of `ggstatsplot` recently, but need to wait for `skimr`'s new version to make it to `CRAN` now since it is also going to break `ggstatsplot`. So, for now, can you please soft-deprecate `sjstats::p_value()`? 

I will let you know once newer version of `ggstatsplot` makes it to `CRAN` so that you can remove that function completely.

**Comment by strengejacke** [comment]
Ok, thanks! I will not remove it completely in the near future, but make sure that, though deprectaed, it still behaves like it did before. Second step would be to directly call `parameter::p_value()` (which currently won't work due to different column names, that would break ggstatsplot code), and then somewhere in the future it will become defunct.
