### ISSUE TITLE
pairwiseComparisons for Chi-Square Tests

### ISSUE THREAD

**Issue by sbalci** [IndrajeetPatil/ggstatsplot#384]
**Describe the solution you'd like**
I think addition of pairwiseComparisons for Chi-Square Tests would be helpful. 

**How could we do it?**

Similar functions I found useful are:

```
RVAideMemoire::chisq.multcomp()
RVAideMemoire::fisher.multcomp()
rmngb::pairwise.chisq.test(x, ...)
rmngb::pairwise.fisher.test(x, ...)
```

**Comment by IndrajeetPatil** [comment]
Update: 
- `rmngb` is archived since those functions don't work anymore:
https://cran.r-project.org/web/packages/rmngb/index.html

- I don't want to rely on a massive dependency like `RVAideMemoire` to support this since as it is, `ggstatsplot` is super-bulky.

I think the core issue is that I am not sure where this would be relevant detail to include or how to even include this any of the visualizations.

There is not much space left on plots to include any other details:

- `ggpiestats` example

![image](https://user-images.githubusercontent.com/11330453/94371374-63b9ae00-00f6-11eb-9a65-15d7408e68db.png)

- `ggbarstats` example

![image](https://user-images.githubusercontent.com/11330453/94371380-6ddbac80-00f6-11eb-9a92-be678515e8aa.png)

I think it will be better for users to carry out this analysis on their own rather than expecting `ggstatsplot` to do it for you.

**Comment by IndrajeetPatil** [comment]
I am thinking more about this and I think it might be better to have a different plot (like a dumbbell chart) to show these pairwise comparisons and then show the stats on the secondary Y-axis.

![image](https://user-images.githubusercontent.com/11330453/113339962-905fb400-932b-11eb-84a2-bd8f28a20dd6.png)

**Comment by sbalci** [comment]
Maybe a second graph showing significant 2x2 groups also works.

for repeated measures (McNemar) I like alluvial, sankey diagrams.

**Comment by IndrajeetPatil** [comment]
Yes, waiting for [this](https://github.com/davidsjoberg/ggsankey) to make it to `CRAN` and then will be easy to support in `ggstatsplot`.

**Comment by sbalci** [comment]
That is I am also waiting for :)

There is also [this package](https://github.com/erblast/easyalluvial). I wished it would be possible to show frequencies and percentages on flows as well.
