### ISSUE TITLE
Feature request: implement Kendall's correlation method in ggcorrmat

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/ggstatsplot#433]
**Describe the solution you'd like**
Add the possibility to chose Kendall's correlation coefficient in `ggcorrmat()`

**How could we do it?**
I didn't look how it is implemented in **ggstatsplot** now, but usually method `"kendall"` is used instead of others in `cor.test()`.

```r
ggcorrmat(data = iris, type = "kendall") 
```

**Comment by IndrajeetPatil** [comment]
This used to be supported in `ggstatsplot`, but I decided against it because I wanted to be consistent across functions in terms of how many tests are supported for each type of statistics (always 1). `ggcorrmat` was exception where it was confusing whether specifying `type == "nonparametric"` was supposed to return Spearman's _rho_ or Kendall's _tau_.

I think a better solution is to use `correlation` package to extract stats details and then use a visualization from a host of packages that support visualization of correlation matrices.
