### ISSUE TITLE
ggwithininstats one-way ANOVA result is not correct

### ISSUE THREAD

**Issue by gbganalyst** [IndrajeetPatil/ggstatsplot#441]
First of all, I love the way the author incorporates ggplot2 syntax and experimental design analysis into this package.

In my curiosity to see if the result is actually correct, I tried to replicate the statistical result of this data
```r
set.seed(123)

library(WRS2)

# plot
ggstatsplot::ggwithinstats(
  data = WineTasting,
  x = Wine,
  y = Taste,
  pairwise.comparisons = TRUE, # show pairwise comparison test results
  title = "Wine tasting",
  caption = "Data source: `WRS2` R package",
  ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE
)
```
![Wine tasting result](https://user-images.githubusercontent.com/34424271/85921858-35b69a80-b877-11ea-8d34-f4b69e41d6dc.jpg)

# One way ANOVA results in R
![One way ANOVA result in R](https://user-images.githubusercontent.com/34424271/85921957-d4db9200-b877-11ea-95f1-fd10616f1112.png)

# One way ANOVA results in SPSS
![One way ANOVA result in SPSS](https://user-images.githubusercontent.com/34424271/85922074-909cc180-b878-11ea-8877-e02e10d92631.png)

Please kindly look into this.

Best,
Ezekiel

**Comment by IndrajeetPatil** [comment]
There is nothing incorrect about the results here. You are treating a within-subjects design as a between-subjects design and expecting the same results.

You get the same result if you use R or any of the other GUI softwares:

- **JASP**

![image](https://user-images.githubusercontent.com/11330453/85930463-cf546b00-b8bc-11ea-84e0-ecbb834d84b1.png)

- **jamovi**

![image](https://user-images.githubusercontent.com/11330453/85930479-07f44480-b8bd-11ea-9a78-ae257af399b0.png)

- **R**

(note here that the F- and p-values are different because they are not corrected for sphericity)

![image](https://user-images.githubusercontent.com/11330453/85930525-5d305600-b8bd-11ea-8b4f-7041ec08366d.png)

**Comment by gbganalyst** [comment]
Dear Indrajeet,

Thank you for the quick response and clear explanation. Everything is actually correct when I used the twin function ggstatsplot::ggbetweenstats().

```r
library(WRS2)

# plot
ggstatsplot::ggbetweenstats(
  data = WineTasting,
  x = Wine,
  y = Taste,
  pairwise.comparisons = TRUE, # show pairwise comparison test results
  title = "Wine tasting",
  var.equal = TRUE,
  caption = "Data source: `WRS2` R package",
  ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE
)
```
# Result with ggstatsplot::ggbetweenstats() 
![comment](https://user-images.githubusercontent.com/34424271/85945496-09158800-b936-11ea-91cf-222e6cdf9453.png)

# Result with base function in R

![comment1](https://user-images.githubusercontent.com/34424271/85945583-c6a07b00-b936-11ea-9378-f554fd512bc1.png)


ggstatsplot package is a great package for experimental design! I am proud of your great effort Indrajeet Patil.
