### ISSUE TITLE
Feature Idea: Automatic determining whether to use "np" or "p"

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#486]
Hey, again, great package. 

I was wondering whether it wouldn't be possible to determine whether a parametric or non-parametric test is needed within, for example, ggwithinstats. Right now, my workflow is to test the data and then choose the right version.

A first idea would be 

```r
# Normality test 
normality_test <- with(data, tapply(dependent_variable, grouping_variable, stat.desc, norm=T))

for(i in normality_test){
  # stat.desc gives a “named number”, extracting the data can be done via [[]], the relevant value is “normtest.p”, which is at the 20th place
  if(!is.null(i)){
    if (i[[20]] < 0.05){
      print("You have to take the non-parametric test.")
      break
    }
    print("You may take the parametric test.")
    }
}
```

Of course, this is a very simple solution and can be probably written much better, but I was just wondering whether sth like this would make sense.

Thanks for considering!

**Comment by IndrajeetPatil** [comment]
I would not be comfortable supporting something like this. 

The package is supposed to be neutral when it comes to different statistical approaches; it defaults to `parametric` only because that has been the most traditionally dominant approach, but also complements it with the Bayesian approach. The package also supports `robust` statistical approaches and there is no clear guidelines I can offer about when to prefer `nonparametric` or `robust` over `parametric` or `bayesian`. I'd be more comfortable leaving this to the user. 

Also, it seems like there is a clear way to extend the existing functions by writing wrappers around them.
