### ISSUE TITLE
SD and mean value in plots 

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#494]
Hey, as a feature idea, would it be useful to show the sd as a value besides the mean value, e.g. in within-stats?

**Comment by IndrajeetPatil** [comment]
The central measure plotting in `ggbetweenstats` and `ggwithinstats` will be changing completely in the next release.

![image](https://user-images.githubusercontent.com/11330453/102643838-29453780-4160-11eb-97c4-9c27b9388456.png)

In light of that, I don't think it makes sense to display SD information since there will not be anything similar to other central tendency methods.
