### ISSUE TITLE
average shown as median and not as average

### ISSUE THREAD

**Issue by pavlo888** [IndrajeetPatil/ggstatsplot#516]
When using the ggstatsplot::ggbetweenstats function, the average is shown as "µmedian" instead of "µmean". Any idea what could be going wrong? 

This is the code I am using: 
```r
ggstatsplot::ggbetweenstats(
  data = stem_2020,
  x = symptom,
  grouping.var = object,
  y = thickness,
  type = "np",
  pairwise.comparisons = TRUE,
  ggsignif.args = list(textsize = 3, tip_length = 0.01),
  k = 3,
  mean.label.args = list(size = 4),
  outlier.tagging = TRUE,
  outlier.label = plnr,
  title = "Stem thickness 2020",
  ylab = "Stem thickness (mm)",
  palette = "default_jama",
  package = "ggsci",
  plotgrid.args = list(nrow = 1),
  ggtheme = ggthemes::theme_pander(base_size = 22),
)
#> Registered S3 methods overwritten by 'lme4':
#>   method                          from
#>   cooks.distance.influence.merMod car 
#>   influence.merMod                car 
#>   dfbeta.influence.merMod         car 
#>   dfbetas.influence.merMod        car
#> Error in dplyr::select(., {: object 'stem_2020' not found
```

**Comment by IndrajeetPatil** [comment]
This is actually the default behavior since `0.6.8` release. This was done to reflect that different statistical approaches have different centrality tendency measures that they endorse. Sorry about this change in behavior.

<img width="765" alt="Screenshot 2021-02-07 at 08 44 29" src="https://user-images.githubusercontent.com/11330453/107140201-cf235000-6920-11eb-8c5e-a319783ec41f.png">

Also, note that `mean.label.args` argument now needs to be changed to `centrality.label.args`.

**Comment by IndrajeetPatil** [comment]
For next release, if you want to do this, you can do the following:

``` r
library(ggstatsplot)

ggbetweenstats(mtcars, am, wt, type = "np", centrality.type = "p")
```

![](https://i.imgur.com/feu7Nn7.png)

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
