### ISSUE TITLE
Request: correction abbreviated as option

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#550]
Hey there, I am often having experiments with ~8 or 10 conditions. Using the Friedman's test (for example), sometimes gives many significant differences. I use Bonferroni-correction and everything works great. 

However, with many comparisons, the figure is cluttered. I was wondering whether one could either
1: only show the correction at the bottom (like the pairwise-test: Durbin-Conover, for example) or
2: abbreviate the correction (e.g.: "Bonferroni-corrected" to "Bonf.-corr.")

I would let the default option as is today, but would appreciate such an option to make it more readable.

Thanks for considering.

**Comment by IndrajeetPatil** [comment]
In general, I am a bit reluctant to provide arguments to change different aspects of the plot. The default plots in `ggstatsplot` are complex and contain so many layers that providing an option to change most aspects of it would lead to a highly complicated and unsustainable API. (For example, others have requested to change aspects of the subtitle expression, others want options to change caption expression, etc.). 

So I have instead created smaller packages (`statsExpressions` for expressions that can be customized by users, `pairwiseComparisons` for pairwise comparisons, etc.) to increase customizability of `ggstatsplot`, and that's what I will continue working on instead of complicating the current API, which is already bloated as it is. I hope this rationale makes sense.

My solution to your specific problem is going to be the same as here. If you feel the *p*-value displays are too cluttered, you can switch to asterisk conventions, or some other convention. `pairwiseComparisons` package will help you customize this further.
https://github.com/IndrajeetPatil/ggstatsplot/issues/544#issuecomment-804356525

**Comment by M-Colley** [comment]
Thanks!
