### ISSUE TITLE
Centrality Text Customisation

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/ggstatsplot#557]
Could it be documented somewhere how to customise the centrality text? For example,

![image](https://user-images.githubusercontent.com/631218/113819405-9981d280-97bc-11eb-82c7-88bed50564da.png)

**Comment by IndrajeetPatil** [comment]
This is not possible to customize, nor will I consider providing arguments to customize this further because customizing every little aspect of the plot will lead to an explosion of arguments. Additionally, the centrality measure is not always mean, it can be median, trimmed mean, or a MAP estimate. So I want the label to be informative in that respect.

You can customize the plot yourself if you wish to change the centrality label. Something like this is a good start:

``` r
library(ggstatsplot)
library(tidyverse)

p <- ggbetweenstats(mtcars, am, wt, centrality.plotting = FALSE)

df <- 
  mtcars %>%
  mutate(am = as.factor(am)) %>%
  select(am, wt) %>%
  tidyr::drop_na() %>%
  group_by(am) %>%
  group_modify(
    .f = ~ parameters::standardize_names(
      data = as.data.frame(suppressWarnings(parameters::describe_distribution(x = .))),
      style = "broom"
    )
  ) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(label = paste0("list(~bar(x)=='", insight::format_value(estimate, 2), "')")) %>%
  ungroup() %>%
  rename(wt = estimate)

p +
  rlang::exec(
    .fn = ggplot2::geom_point,
    mapping = ggplot2::aes(x = am, y = wt),
    data = df,
    inherit.aes = FALSE
  ) +
  rlang::exec(
    .fn = ggrepel::geom_label_repel,
    data = df,
    mapping = ggplot2::aes(x = am, y = wt, label = label),
    min.segment.length = 0,
    inherit.aes = FALSE,
    parse = TRUE
  )
```

![](https://i.imgur.com/W15sCB4.png)

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by RS-eco** [comment]
Is there also a simple way of implementing this with grouped_ggbetweenstats?
