### ISSUE TITLE
how to connect items/subjects in ggwithinstats 

### ISSUE THREAD

**Issue by danielemarinazzo** [IndrajeetPatil/ggstatsplot#584]
Hi

going through the example and the vignette I don't seem to find how to connect the same subjects across measures (like in the third example of the vignette and in the second example of the readme).

thanks!

**Comment by IndrajeetPatil** [comment]
Unfortunately, you don't have much control over this.

**If there are two groups, the repeated observations will be connected with each other.**

``` r
library(ggstatsplot)
ggwithinstats(VR_dilemma, modality, score)
```

![](https://i.imgur.com/dOs8LLO.png)

**If there are more than two groups, they won't be (because the plot then gets too cluttered to be useful).**

``` r
ggwithinstats(WRS2::WineTasting, Wine, Taste)
```

![](https://i.imgur.com/R6wWcrF.png)

<sup>Created on 2021-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In future, you might also be able to select a specific variable by which you can connect the observations to each other:
**https://github.com/IndrajeetPatil/ggstatsplot/issues/483**
