### ISSUE TITLE
Is it possible to change color palette for ggscatterstats?

### ISSUE THREAD

**Issue by yech1990** [IndrajeetPatil/ggstatsplot#59]
I notice that custom color palette can be passed to the plot by argument `package=xxx, palette=xxx` .

It works in most function of  ggstatsplot, but seems that it is impossible to pass that argument to `ggscatterstats`.

Here is the error message:

```R
Error in ggscatterstats(., , : unused argument (package = "ggsci")
```

**Comment by IndrajeetPatil** [comment]
@yech1990 Hmm, it is true that this is a bit of an inconsistent behavior on `ggstatsplot`'s part, but I've deliberately not included those arguments for `ggscatterstats` because there are only two colors, which are already being specified by arguments `xfill` and `yfill`.

One possible thing I can do is change `xfill` and `yfill` defaults to `NULL` and as long as they are not specified, 2 colors from a given `package` and `palette` can be retrieved. Does that like a reasonable approach?

P.S. `ggcorrmat` doesn't have these arguments either.

**Comment by IndrajeetPatil** [comment]
Setting either `xfill` or `yfill` to `NULL` will now deactivate manual specification of colors and `package` and `palette` arguments will come into effect.

``` r
ggstatsplot::ggscatterstats(
  data = mtcars,
  x = wt,
  y = mpg,
  xfill = NULL,
  package = "wesanderson",
  palette = "Royal1"
)
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
```

![](https://i.imgur.com/c9I6NcC.png)

<sup>Created on 2018-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, this is something that I want to implement for sure. But this will not be part of `0.0.6` release. Probably `0.0.7` or `0.0.8`.
