### ISSUE TITLE
Caption parameter not working

### ISSUE THREAD

**Issue by chabrault** [IndrajeetPatil/ggstatsplot#611]
It seems that there is a problem with "caption" parameter, at least with `ggbetweenstats` and `ggwithinstats` functions. Specifying `caption=NULL` or `caption=""` does not have an effect and caption remains (with the text "Pairwise test: ...").

```r
# plot
ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species",
  caption=NULL
)
```
![Rplot_ggbetweenstats](https://user-images.githubusercontent.com/37081971/122080240-6bdd8900-cdfe-11eb-9c0c-708ba4928e1e.png)

It is still possible to remove caption by adding to the plot `p + labs(caption=NULL)`.
Thank you for your package!

Session Info:
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

**Comment by IndrajeetPatil** [comment]
You mention the solution in your issue:

``` r
library(ggstatsplot)
library(ggplot2)

ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species"
) +
  labs(caption = NULL)
```

![](https://i.imgur.com/cnWlDHe.png)

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Setting `caption = NULL` won't work because it is already being used internally to display important details in the caption. Whatever you provide to `caption` will just be added _on top of that_ info.
