### ISSUE TITLE
Nonlinear smooth for scatterstats

### ISSUE THREAD

**Issue by ShixiangWang** [IndrajeetPatil/ggstatsplot#617]
Is it possible to open the smooth args for scatterstats? The `method` field is not supported in `smooth.line.args` option. I think it would be useful to support all smooth methods in scatterstats.

```r
set.seed(123)
library(ggstatsplot)

# creating dataframe with rownames converted to a new column
mtcars_new <- as_tibble(mtcars, rownames = "car")

# simple function call with the defaults
if (require("ggExtra")) {
    ggscatterstats(
        data = mtcars_new,
        x = wt,
        y = mpg,
        label.var = car,
        label.expression = wt < 4 & mpg < 20,
        # making further customization with `ggplot2` functions
        ggplot.component = list(ggplot2::geom_rug(sides = "b")), smooth.line.args = list(method = stats::loess)
    )
}
```

**Comment by IndrajeetPatil** [comment]
This used to be supported, but I removed it because the statistics shown in the subtitle doesn't adjust to these changes. 

But, if someone explicitly specifying them, we can assume that they know what they are doing? At any rate, you can change the method now:

``` r
library(ggstatsplot)
ggscatterstats(mtcars, wt, mpg, 
               smooth.line.args = list(method = "loess", formula = y ~ x))
```

![](https://i.imgur.com/KgUPJUI.png)

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ShixiangWang** [comment]
Thanks.
