### ISSUE TITLE
How the value of the parameter of the test (number in parenthesis) is chosen?

### ISSUE THREAD

**Issue by javierfs** [IndrajeetPatil/ggstatsplot#638]
I am not sure if this is the right place to ask this... but I am wondering how the value of the parameter of the test (number in parenthesis) is chosen. For example: 

![](https://indrajeetpatil.github.io/ggstatsplot/reference/figures/README-ggbetweenstats1-1.png)

How the number in parenthesis of the F_welch is chosen: 2,92.21?

PS: How can I display the Bayesian statistics at the bottom of the chart? 

Example: 

![lead_genre_monthlystreams_listenters_vertical_9_7](https://user-images.githubusercontent.com/13203962/126214399-699ff285-9865-4742-a6d2-e7c930f0ae98.png)

This is the code I use to get such a chart: 

```
p1 <- data_cleaned %>% 
  select(monthly_stream30_followers, genre_1) %>% 
  ggbetweenstats(
  x = genre_1,
  y = monthly_stream30_followers,
  xlab = "Lead Genre", # label for the x-axis
  ylab = "Monthly Listeners Streams >30s", # label for the y-axis
  title = "",
  pairwise.comparisons = FALSE,
  ggplot.component =
    # modify further with `ggplot2` functions
  list(
    scale_color_manual(values = paletteer::paletteer_c("ggthemes::Green-Blue Diverging",colourCount_genre_1)),
    theme(axis.text.x = element_text(angle = 0)))
  ) + 
  scale_y_continuous(limits = c(0,7500)) +
  coord_flip() 
  
  p1 + ggsave(here('eda_graphs/',paste0('lead_genre_monthlystreams_listenters_vertical_6_7','.png')),
               height = 6, 
               width = 7,
         device = "png")
```

**Comment by IndrajeetPatil** [comment]
Hi, I would highly recommend that you read the documentation for the primary functions that provides this information:
https://indrajeetpatil.github.io/ggstatsplot/articles/

To address your first question, the function is `ggbetweenstats`: 
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html#summary-of-tests-1

As this shows, the Welch's ANOVA is run via `stats::oneway.test`, so that's where those values come from:

<img width="1345" alt="Screenshot 2021-07-19 at 21 17 03" src="https://user-images.githubusercontent.com/11330453/126214721-051bc74c-9689-4fd7-a099-87ff1c525632.png">

As for your second question, I have no idea. It should show the Bayesian analysis as well, unless the analysis failed for some reason. You can use `https://indrajeetpatil.github.io/ggstatsplot/reference/extract_stats.html` function to extract dataframes. If `$caption_data` is `NULL`, the analysis failed to run.

**Comment by javierfs** [comment]
> Hi, I would highly recommend that you read the documentation for the primary functions that provides this information:
> https://indrajeetpatil.github.io/ggstatsplot/articles/
> 
> To address your first question, the function is `ggbetweenstats`:
> https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html#summary-of-tests-1
> 
> As this shows, the Welch's ANOVA is run via `stats::oneway.test`, so that's where those values come from:
> 
> <img alt="Screenshot 2021-07-19 at 21 17 03" width="1345" src="https://user-images.githubusercontent.com/11330453/126214721-051bc74c-9689-4fd7-a099-87ff1c525632.png">
> 
> As for your second question, I have no idea. It should show the Bayesian analysis as well, unless the analysis failed for some reason. You can use [this](https://indrajeetpatil.github.io/ggstatsplot/reference/extract_stats.html) function to extract dataframes. If `$caption_data` is `NULL`, the analysis failed to run.

I am pretty new with R. This extract_stats script is not included in your package right? How can I use it? I downloaded it and put it in the same path as the working directory but still it cannot recognise the function. 

Thanks a lot for the support!
