### ISSUE TITLE
Unable to install the package for R version 3.6.3

### ISSUE THREAD

**Issue by ufangYang** [IndrajeetPatil/ggstatsplot#667]
Is it possible to install 'ggstatsplot' for R version 3.6.3?  I received this error message during installing the package: `package ‘ggcoefstats’ is not available (for R version 3.6.3)`. Would be looking forward to implementing this package on this R version. Thanks!

**Comment by IndrajeetPatil** [comment]
Hi,

I had to bump the needed version because all the testing infrastructure for the package has now moved to R versions > 4.0, and so didn't want to risk supporting earlier versions. I will see if I can downgrade the needed version and if that creates any issues.

Out of curiosity, why do you prefer not updating to the latest R version?

**Comment by IndrajeetPatil** [comment]
Since I haven't heard any pushback from other users for changing the minimum R version nor have I heard good reasons from you to not upgrade to `R 4.0`, I am going to keep the minimum version as it is now.
