### ISSUE TITLE
No plot.type in ggwithinstats

### ISSUE THREAD

**Issue by AntoineSoetewey** [IndrajeetPatil/ggstatsplot#670]
Thanks again for this amazing package!

I see that there is a possibility to specify the plot.type in ggbetweenstats, but not in ggwithinstats. Any reason for this?

Do you think it would be possible to add it?

Thanks in advance for your time.

Regards,
Antoine

**Comment by IndrajeetPatil** [comment]
The reason is that I can't seem to make up my mind about whether `ggwithinstats()` should get `plot.type` argument, or whether this argument should be retired for  `ggbetweenstats()`.

I am not happy with having that argument because it complicates the implementation, and I also don't see the value of making box plots with `{ggstatsplot}` when they are so easy to make outside it. But, on the other hand, a number of users already seem to be using this argument, so difficult to make such a drastic breaking change this late. 

So I might just end up adding `plot.type` argument `ggwithinstats()`  🤷 

Thanks for forcing me to clarify my thoughts on this 😅

**Comment by AntoineSoetewey** [comment]
Thanks for your answer.

Food for thoughts: Boxplots are quite "standard" in introductory statistic classes, but not violin plots. So students generally understand boxplots, but struggle to understand violin plots (and struggle even more to understand the combination of boxplots and violin plots).

In the same sense of  https://github.com/IndrajeetPatil/ggstatsplot/issues/669 to increase readability and conciseness, I use `plot.type = "box"` much more often than `plot.type = "violin"` or `plot.type = "boxviolin"`.

I understand that boxplots are easy to make outside of `{ggstatsplot}`, but I really like the fact that with `{ggstatsplot}` it is easy to display the plot **together** with some statistical results (which is not so easy with other packages or in base R).

Moreover, the fact that I can run `ggbetweenstats()` and `ggwithinstats()` on multiple variables at once make the package very useful for my projects. See more information if you wish in this [article](https://statsandr.com/blog/how-to-do-a-t-test-or-anova-for-many-variables-at-once-in-r-and-communicate-the-results-in-a-better-way/#update-with-the-ggstatsplot-package).

Feel free to get in touch if you believe I can help, I'd be happy to contribute!

Regards,
Antoine
