### ISSUE TITLE
potential error with ggbetweenstats argument: outlier.shape = NA 

### ISSUE THREAD

**Issue by TriageDr** [IndrajeetPatil/ggstatsplot#690]
Hi Dr. Patil - love the package, quick question regarding the  outlier.shape = NA  argument of the ggbetweenstats function.

1) When using the ggbetweenstats function, I'm wondering if the outlier.shape = NA argument is being ignored (see bold for code). I've attached a png of the output graphic, clearly showing outliers for the 3rd box-violin plot (green). 

My goal is to not display the outliers (but compute the stats using them!) and therefore shrink the y-axis of the output plot.

```r
  plot <- ggbetweenstats(
      data = data,
      x = x_var,
      y = y_var, 
      outlier.shape = NA,
      pairwise.display = "significant",
      p.adjust.method = "bonferroni",
      results.subtitle = FALSE,
      type = "np",
      ggtheme = theme_ipsum(),
      ggplot.component = list(
        scale_color_carto_d(palette = "Geyser",
                            direction = -1))
      )
```
![image](https://user-images.githubusercontent.com/44305158/148117302-1824734b-6b3b-48a6-b1df-efb095d8e62f.png)

**Comment by IndrajeetPatil** [comment]
`outlier.shape = NA` won't remove the outlier data per se. It just hides it, as you can see from the lingering labels.

``` r
library(ggstatsplot)

ggbetweenstats(
  data = morley,
  x = Expt,
  y = Speed,
  pairwise.comparisons = FALSE,
  outlier.tagging = TRUE,
  outlier.label = Run
)
```

![](https://i.imgur.com/MBH5bl8.png)

``` r
ggbetweenstats(
  data = morley,
  x = Expt,
  y = Speed,
  pairwise.comparisons = FALSE,
  outlier.tagging = TRUE,
  outlier.label = Run,
  outlier.shape = NA
)
```

![](https://i.imgur.com/PaPZh4w.png)

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

> My goal is to not display the outliers (but compute the stats using them!)

I think this is a bad idea. The data plotted should be truthful to the data used for statistical analysis displayed in the plot; otherwise, the statistical analysis is misleading. 

That said, if you _do_ wish to make such a plot, you can remove outliers yourself and then use `{ggstatsplot}`. That way, you won't need to use any additional tricks and plot will be the faithful to the underlying data.
