### ISSUE TITLE
Error Problem with 'mutate()'  column 'isanoutlier' i 'isanoutlier = ifelse()'. x arguments imply differring numer of rows: 0,2

### ISSUE THREAD

**Issue by amita4ai** [IndrajeetPatil/ggstatsplot#691]
I am encountering problem with ggbetweenstats plot. When I run it in R markdown it works perfectly fine without any error but when I knit it in word/html, it throws following error:
Problem with 'mutate()'  column 'isanoutlier' i 'isanoutlier = ifelse()'. x arguments imply differring number of rows: 0,2

```{r}

library(ggstatsplot)

mtcars$am_factor=as.factor(ifelse(mtcars$am==1,"Auto","Manual"))

ggbetweenstats(mtcars, x="am_factor",y="mpg")

```

This is reprex which works in both ways but I am working on some secure could where I cant copy data and commands.

**Comment by IndrajeetPatil** [comment]
Hi,

Unless you can provide me with a reproducible example where this behavior is observed, I can't be convinced that this is a bug.

**Comment by Yvonne27Jin** [comment]
Hi, I've encountered the same problem. When using data "wiki_hot_100s" from package "billboard" for testing, the code and error message are as follows:

`install.packages("billboard") `
`library(billboard)`
`ggstatsplot::ggbetweenstats(data = wiki,x = year,y = no)`

> Error in `mutate()`:
! Problem while computing `isanoutlier = ifelse(...)`.
ℹ The error occurred in group 1: year = 1960.
Caused by error:
! $ operator is invalid for atomic vectors
Run `rlang::last_error()` to see where the error occurred.

> rlang::last_error()
<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `isanoutlier = ifelse(...)`.
ℹ The error occurred in group 1: year = 1960.
Caused by error:
! $ operator is invalid for atomic vectors

Backtrace:
  1. ggstatsplot::ggbetweenstats(data = wiki, x = year, y = no)
 14. base::with.default(...)
 15. base::eval(substitute(expr), data, enclos = parent.frame())
 16. base::eval(substitute(expr), data, enclos = parent.frame())
 19. performance:::check_outliers.default(no, method = "iqr", threshold = list(iqr = outlier.coef))
 21. insight:::get_modelmatrix.default(x)
 23. stats::model.matrix.default(object = x, ...)
 25. stats:::terms.default(object)
 27. x$terms %||% attr(x, "terms")
Run `rlang::last_trace()` to see the full context.
>
