### ISSUE TITLE
ggbetweenstats - hide median labels 

### ISSUE THREAD

**Issue by sergioserrano81** [IndrajeetPatil/ggstatsplot#772]
Hi! In ggbetweenstats, I see the different options around plotting, hiding the statistical results, and labeling the mean. However, I am interested in hiding the mean. Is there a way to achieve this?

Thanks in advance

```r
df <- tibble::as_tibble(mtcars)

df <- ggbetweenstats(
  data = df,
  results.subtitle = FALSE,  #hide statistical output
  x = "cyl",
  y = "mpg") 

df
```

**Comment by AntoineSoetewey** [comment]
`centrality.plotting = FALSE` should do the trick

**Comment by IndrajeetPatil** [comment]
Almost.

You can remove it by setting `centrality.plotting = FALSE`:
https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

<img width="812" alt="Screenshot 2022-07-20 at 20 12 06" src="https://user-images.githubusercontent.com/11330453/180053134-13f11e8e-0db2-47ab-ab83-546e7dbe2000.png">

**Comment by IndrajeetPatil** [comment]
Also, please don't use quoted variables. Instead do:

```r
x = cyl,
y = mpg
```

**Comment by sergioserrano81** [comment]
It worked! Thank you so much.

**Comment by AntoineSoetewey** [comment]
I initially thought it was `centrality.plotting` instead of `mean.plotting` (See the history of my comment). However based on the documentation [here](https://www.rdocumentation.org/packages/ggstatsplot/versions/0.9.3/topics/ggbetweenstats):

![24BCA038-C0B1-41E1-8EAA-9E05E3400B43](https://user-images.githubusercontent.com/17910063/180053788-efff8a86-c511-476f-87c9-bdb55e1eeb53.png)

I edited my comment. Do you know where this inconsistency comes from @IndrajeetPatil ?

**Comment by IndrajeetPatil** [comment]
It is possible that you are looking at the cached version of the page, because if I follow the link you sent me, I see `centrality.plotting`.

That said, DataCamp's rdocumentation makes a new version of the pages for each package release. So it is likely that you were seeing a version before 0.7.0, which is when this change (`mean.plotting` -> `centrality.plotting`) was introduced.

**Comment by AntoineSoetewey** [comment]
Makes sense, I also see `centrality.plotting` after clearing my cache. Thanks!
