### ISSUE TITLE
ggbetweenstats violin with two groups (the keyword `y` is a list)

### ISSUE THREAD

**Issue by sunshineYin** [IndrajeetPatil/ggstatsplot#850]
Thanks for your excellent work on this package! And I am trying to draw a violin plot with `ggbetweenstats` function. The example code is as follows:

```
set.seed(123)

ggbetweenstats(
  data  = iris,
  x     = Species,
  y     = Sepal.Length,
  title = "Distribution of sepal length across Iris species"
)
```

So, the example code's keyword `y` is only one column/field, right? But I want to show two violins for each x/Species. That is, `y` needs to be a list. So how to achieve? And Thanks a lot!

The expected form is as follows:
![image](https://user-images.githubusercontent.com/34116217/231739952-1c312172-68d0-4879-ae43-c441e9ae82d3.png)

**Comment by IndrajeetPatil** [comment]
Hi,

Thanks for the report.

Because the statistical engine for `ggbetweenstats()` is designed to only deal with one-way designs, the visualization also supports only one-way designs. There are no plans to support more complex designs in `{ggstatsplot}`.

You can just prepare such plots using `{ggplot2}` itself, or have a look at a myriad of [other extensions](https://exts.ggplot2.tidyverse.org/gallery/) that support such visualizations.
