### ISSUE TITLE
text = element_text(size = .) can not change sample size label size

### ISSUE THREAD

**Issue by zhengchencai** [IndrajeetPatil/ggstatsplot#883]
Hi there,

I wonder how to change the font size for sample size (n = 10) in general in ggstatsplot. text = element_text(size = .)  in theme() does not work. I see the sample size label is 4 by default https://github.com/IndrajeetPatil/ggstatsplot/blob/3ccd43c6e18a568602ed71be8bac14bcbe6a720e/R/ggbarstats.R#L163.  How can I change it after for instance a ggbarstats plot. I tried both text and axis.text, but it did not work. 

```
ggbarstats(mtcars, x = vs, y = cyl) + theme(text = element_text(size = 24, face = "plain", color = "black"))
```

```
ggbarstats(mtcars, x = vs, y = cyl) + theme(axis.text = element_text(color = "black", size = 24))
```

Also, the previous default p value for proportion.test is *** or ns, not it is the exact p value, how can I change the font size of it and switch to levels by ***? 

Thanks a lot.

**Comment by IndrajeetPatil** [comment]
With the new release (`0.12.1`), you can pass additional args to `geom_text()` to change sample size label:

``` r
library(ggstatsplot)

ggbarstats(mtcars, am, cyl, sample.size.label.args = list(size = 5))
```

![](https://i.imgur.com/nZ70Duh.png)

<sup>Created on 2023-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

> Also, the previous default p value for proportion.test is *** or ns, not it is the exact p value, how can I change the font size of it and switch to levels by ***?

No, this is not something that I plan to support because it is arbitrary and discipline-specific.
