### ISSUE TITLE
Pairwise comparisons not showing 

### ISSUE THREAD

**Issue by Antros89** [IndrajeetPatil/ggstatsplot#904]
Running ggbetweenstats not longer shows pairwise comparisons between groups irrespective if the comparison is not significant or not

**Comment by IndrajeetPatil** [comment]
Can you please post a reproducible example?

**Comment by Antros89** [comment]
I am using the example provided in the vignette:

set.seed(123)
library(PMCMRplus) 

# create a plot
p <- ggbetweenstats(mtcars, am, mpg,
                    pairwise.display = "all")
p

**Comment by IndrajeetPatil** [comment]
Oh, you are not seeing any comparisons because there are only two groups present. Multiple comparisons are relevant when there are more than two groups present.

---

``` r
set.seed(123)
library(ggstatsplot)
#> You can cite this package as:
#>      Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
#>      Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167

ggbetweenstats(mtcars, am, mpg, pairwise.display = "all")
```

![](https://i.imgur.com/B9oHesY.png)

``` r

ggbetweenstats(mtcars, cyl, mpg, pairwise.display = "all")
```

![](https://i.imgur.com/S4lJCgA.png)

<sup>Created on 2023-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
