### ISSUE TITLE
Change in palette

### ISSUE THREAD

**Issue by Emanuel-1986** [IndrajeetPatil/ggstatsplot#914]
Hi,
 
I am trying to change the background of the ggpiestats to illustrate the percentage of an ordinal variable composed of 4 levels on a single pie chart. So, I would like to use a sequentially coloured background. My code is:

```r
E1 <- E1 %>%mutate(Pain.discomfort=factor(Pain.discomfort,levels=c("I have no pain or discomfort", "I have slight pain or discomfort", "I have moderate pain or discomfort", "I have severe pain or discomfort")))

P1 <- ggpiestats(data = E1, Pain.discomfort, title = "Overall prevalence", bf.message = FALSE, legend.title = "Pain", type = "nonparametric", package = "ggsci", palette = "default_frontiers") + theme(plot.title = element_text(size = 15), plot.subtitle = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 12), legend.position = "none") + guides(alpha = "none")
P1
```

However, when I am trying to input "default_frontiers" rather than "category10_d3", R gives me:

Error in length[[1L]] : subscript out of bounds

Your help is greatly appreciated.

Emanuel

**Comment by IndrajeetPatil** [comment]
I don't think this is related to `ggpiestats()`. Both of those palettes work just fine. The source error is probably somewhere else. Can't help further because you didn't provide a reproducible example.

---

``` r
library(ggstatsplot)

ggpiestats(mtcars, am, cyl, package = "ggsci", palette = "category10_d3")
```

![](https://i.imgur.com/rdhWSdV.png)

``` r

ggpiestats(mtcars, am, cyl, package = "ggsci", palette = "default_frontiers")
```

![](https://i.imgur.com/BFpvt63.png)

<sup>Created on 2024-03-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
