### ISSUE TITLE
grouped_ggbetweenstats Statistic Choice May Vary Between Groups

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/ggstatsplot#942]
Ideally, it would be nice to use the statistic used for three or more groups also for two groups for consistency.

![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/631218/b0af9e3c-a27b-44ba-98ca-242451e03000)

In this example, Kruskal–Wallis test could be used for both groups, unlike Mann-Whitney. An option for consistency would be good.

**Comment by IndrajeetPatil** [comment]
It's all [linear models underneath](https://lindeloev.github.io/tests-as-linear/), so, in principle, I agree with you.

But `{ggstatsplot}` completely disregards that fact and uses different tests based on the structure of data. In case of group comparisons, which statistical test is carried out is decided based on whether there are two or more than two groups. Because of this heuristic, there is currently no way to support what you have in mind. In fact, even if you introduce an empty group in `x` just to fool the function into thinking that there are three groups, the function is going to drop that empty group.

The only way this could be supported is by allowing the user to decide which test to run, but that opens a whole new can of worms: there'll be a combinatorial explosion of unhappy paths from crossing supplied data with chosen statistical analysis.
